import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppNavigation from "@/partial/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Juan David Mahecha Cruz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          {children}
        </div>


        <footer>
          <AppNavigation></AppNavigation>
        </footer>

      </body>

    </html>
  );
}
